<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
  /**
   * Seed the application's database.
   *
   * @return void
   */
  public function run()
  {
    $this->call([
      RoleSeeder::class,
      LanguageSeeder::class,
      JobSeeder::class,
      PositionSeeder::class,
      UserSeeder::class,
      DepartmentSeeder::class,
      ActivitySeeder::class,
      EducationSeeder::class,
    ]);

    $department_user = array(
      array('department_id' => '1','user_id' => '1','leader' => '0'),
      array('department_id' => '1','user_id' => '2','leader' => '1'),
      array('department_id' => '2','user_id' => '3','leader' => '1'),
      array('department_id' => '3','user_id' => '4','leader' => '1'),
      array('department_id' => '3','user_id' => '30','leader' => '0'),
      array('department_id' => '3','user_id' => '31','leader' => '0'),
      array('department_id' => '4','user_id' => '50','leader' => '0'),
      array('department_id' => '4','user_id' => '56','leader' => '0'),
      array('department_id' => '5','user_id' => '6','leader' => '1'),
      array('department_id' => '5','user_id' => '21','leader' => '0'),
      array('department_id' => '5','user_id' => '25','leader' => '0'),
      array('department_id' => '5','user_id' => '26','leader' => '0'),
      array('department_id' => '5','user_id' => '27','leader' => '0'),
      array('department_id' => '5','user_id' => '28','leader' => '0'),
      array('department_id' => '6','user_id' => '7','leader' => '1'),
      array('department_id' => '6','user_id' => '20','leader' => '0'),
      array('department_id' => '7','user_id' => '8','leader' => '1'),
      array('department_id' => '7','user_id' => '44','leader' => '0'),
      array('department_id' => '7','user_id' => '45','leader' => '0'),
      array('department_id' => '7','user_id' => '62','leader' => '0'),
      array('department_id' => '8','user_id' => '9','leader' => '1'),
      array('department_id' => '8','user_id' => '22','leader' => '0'),
      array('department_id' => '8','user_id' => '23','leader' => '0'),
      array('department_id' => '8','user_id' => '24','leader' => '0'),
      array('department_id' => '9','user_id' => '9','leader' => '1'),
      array('department_id' => '9','user_id' => '37','leader' => '0'),
      array('department_id' => '9','user_id' => '38','leader' => '0'),
      array('department_id' => '9','user_id' => '39','leader' => '0'),
      array('department_id' => '9','user_id' => '40','leader' => '0'),
      array('department_id' => '9','user_id' => '41','leader' => '0'),
      array('department_id' => '9','user_id' => '42','leader' => '0'),
      array('department_id' => '9','user_id' => '52','leader' => '0'),
      array('department_id' => '9','user_id' => '59','leader' => '0'),
      array('department_id' => '9','user_id' => '61','leader' => '0'),
      array('department_id' => '10','user_id' => '10','leader' => '1'),
      array('department_id' => '10','user_id' => '54','leader' => '0'),
      array('department_id' => '11','user_id' => '11','leader' => '1'),
      array('department_id' => '11','user_id' => '33','leader' => '0'),
      array('department_id' => '11','user_id' => '34','leader' => '0'),
      array('department_id' => '11','user_id' => '57','leader' => '0'),
      array('department_id' => '12','user_id' => '12','leader' => '1'),
      array('department_id' => '12','user_id' => '46','leader' => '0'),
      array('department_id' => '12','user_id' => '47','leader' => '0'),
      array('department_id' => '12','user_id' => '48','leader' => '0'),
      array('department_id' => '12','user_id' => '49','leader' => '0'),
      array('department_id' => '12','user_id' => '51','leader' => '0'),
      array('department_id' => '12','user_id' => '55','leader' => '0'),
      array('department_id' => '12','user_id' => '58','leader' => '0'),
      array('department_id' => '13','user_id' => '13','leader' => '1'),
      array('department_id' => '13','user_id' => '14','leader' => '0'),
      array('department_id' => '13','user_id' => '15','leader' => '0'),
      array('department_id' => '13','user_id' => '16','leader' => '0'),
      array('department_id' => '14','user_id' => '17','leader' => '0'),
      array('department_id' => '14','user_id' => '29','leader' => '0'),
      array('department_id' => '15','user_id' => '32','leader' => '0'),
      array('department_id' => '16','user_id' => '43','leader' => '0'),
      array('department_id' => '17','user_id' => '5','leader' => '0'),
      array('department_id' => '17','user_id' => '18','leader' => '0'),
      array('department_id' => '17','user_id' => '19','leader' => '0'),
      array('department_id' => '17','user_id' => '56','leader' => '0'),
      array('department_id' => '1','user_id' => '35','leader' => '0'),
      array('department_id' => '1','user_id' => '53','leader' => '0'),
      array('department_id' => '19','user_id' => '2','leader' => '1'),
      array('department_id' => '20','user_id' => '10','leader' => '1'),
      array('department_id' => '24','user_id' => '44','leader' => '0'),
      array('department_id' => '24','user_id' => '45','leader' => '0'),
      array('department_id' => '24','user_id' => '8','leader' => '1'),
      array('department_id' => '14','user_id' => '5','leader' => '0'),
      array('department_id' => '3','user_id' => '29','leader' => '0'),
      array('department_id' => '4','user_id' => '5','leader' => '1'),
      array('department_id' => '3','user_id' => '63','leader' => '0'),
      array('department_id' => '17','user_id' => '4','leader' => '1'),
      array('department_id' => '15','user_id' => '4','leader' => '1'),
      array('department_id' => '16','user_id' => '4','leader' => '1'),
      array('department_id' => '7','user_id' => '64','leader' => '0')
    );

    foreach ($department_user as $table) {
      DB::table('department_user')->insert([
        'department_id' => $table['department_id'],
        'user_id' => $table['user_id'],
      ]);
    }

    $details = array(
      array('id' => '1','user_id' => '2','birth_date' => '1990-01-28 12:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'г. Душанбе,ул. Сохили, д. 5, кв. 5','email' => 'hr.tjk@evolet.co.uk','tel_1' => '98 888 0077','tel_2' => '55 085 0077','family_status' => 'Женат','children' => NULL,'created_at' => '2024-01-28 21:46:34','updated_at' => '2024-02-06 17:31:25'),
      array('id' => '2','user_id' => '3','birth_date' => '1990-01-11 12:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'г.Душанбе,ул. Бобо Хамдам, д1/1, кв 21','email' => 'nozim.khakimov@evolet.co.uk','tel_1' => '98 710-98-42','tel_2' => NULL,'family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-06 18:10:02','updated_at' => '2024-02-06 18:10:02'),
      array('id' => '3','user_id' => '4','birth_date' => '1988-01-05 00:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'РТ, г.Душанбе,ул.Маяковского 93,кв.69','email' => 'firdavs.kilichbekov@evolet.co.uk','tel_1' => '934549554','tel_2' => '934348334','family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-06 18:13:06','updated_at' => '2024-03-14 10:51:25'),
      array('id' => '4','user_id' => '5','birth_date' => '1990-02-08 12:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'г. Душанбе, ул. Н. Махсума 7/1 кв. 28','email' => 'vokhid.azimjon@evolet.co.uk','tel_1' => '98 520 6191','tel_2' => '98 550 2222','family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-06 18:21:19','updated_at' => '2024-02-06 18:21:19'),
      array('id' => '5','user_id' => '6','birth_date' => '1991-03-23 12:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'г. Душанбе, ул. Б Гафурова, д. 33/3 кв 70','email' => 'parviz.pdd@evolet.co.uk','tel_1' => '50 113 3770','tel_2' => '50 160 9987','family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-06 18:34:15','updated_at' => '2024-02-06 18:34:15'),
      array('id' => '6','user_id' => '7','birth_date' => '1972-08-05 13:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'город Душанбе, ул.Гипрозем д.7 кв.27','email' => 'tmabstragan@gmail.com','tel_1' => '918626127','tel_2' => '935626127','family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-06 18:39:10','updated_at' => '2024-02-06 18:39:10'),
      array('id' => '7','user_id' => '8','birth_date' => '1993-05-25 13:00:00','gender' => 'Мужской','nationality' => 'Узбек','citizenship' => 'РТ','address' => 'г. Душанбе, ул Зарафшан, д8, кв. 104','email' => 'a.dzhabarov@evolet.co.uk','tel_1' => '90 150 4935','tel_2' => '90 150 4935','family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-06 18:43:25','updated_at' => '2024-02-06 18:43:25'),
      array('id' => '8','user_id' => '9','birth_date' => '1990-04-05 13:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'Душанбе, ул. Кл. Цеткина д 14/1 кв. 17','email' => 'jomi.sultonzoda90@gmail.com','tel_1' => '917 29 2403','tel_2' => '91 533 1020','family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-06 18:47:27','updated_at' => '2024-02-06 18:47:27'),
      array('id' => '9','user_id' => '10','birth_date' => '1993-10-09 13:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'ул. Нахимов 64/1','email' => 'ino1361@mail.ru','tel_1' => '93 842 3535','tel_2' => '50 204 0475','family_status' => 'Не женат','children' => NULL,'created_at' => '2024-02-06 18:53:58','updated_at' => '2024-02-06 18:53:58'),
      array('id' => '10','user_id' => '11','birth_date' => '1989-01-29 12:00:00','gender' => 'Женский','nationality' => 'Таджичка','citizenship' => 'РТ','address' => 'г. Душанбе,ул.Ахмади Дониш 32/1 кв.50','email' => 'p.mirakhmedova@evolet.co.uk','tel_1' => '93 572 1248','tel_2' => '917 52 1155','family_status' => 'Не замужем','children' => NULL,'created_at' => '2024-02-06 21:01:08','updated_at' => '2024-02-06 21:01:08'),
      array('id' => '11','user_id' => '12','birth_date' => '1988-09-28 13:00:00','gender' => 'Мужской','nationality' => 'таджик','citizenship' => 'РТ','address' => 'г. Душанбе, ул. Нусратулло Махсум 6/3','email' => 'mirzoev88@me.com','tel_1' => '918556464','tel_2' => NULL,'family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-06 21:09:33','updated_at' => '2024-02-06 21:09:33'),
      array('id' => '12','user_id' => '13','birth_date' => '1984-01-08 12:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'Р-н Фирдавси, м. Рохи Нав, г. Душанбе','email' => 'mdsirojov@yahoo.com','tel_1' => '888666984','tel_2' => NULL,'family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-06 21:14:20','updated_at' => '2024-02-06 21:14:47'),
      array('id' => '13','user_id' => '14','birth_date' => '1995-04-09 13:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'ул. Асадулло Гуломов,д. 11/4, кв.29','email' => 'farrukh.kayumov@evolet.co.uk','tel_1' => '901 077070','tel_2' => NULL,'family_status' => 'Не женат','children' => NULL,'created_at' => '2024-02-06 21:21:13','updated_at' => '2024-02-06 21:21:13'),
      array('id' => '14','user_id' => '15','birth_date' => '1997-01-20 12:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'ул. Фирдавси, д. 117,  кв. 67','email' => 'farizmirzo@evolet.co.uk','tel_1' => '550659933','tel_2' => NULL,'family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-06 21:29:16','updated_at' => '2024-02-06 21:29:16'),
      array('id' => '15','user_id' => '16','birth_date' => '1998-10-18 13:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'ул. Насрутолло Махсум д. 77/5 А','email' => 'behruz.muzaffar@outlook.com','tel_1' => '938889166','tel_2' => NULL,'family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-06 21:37:55','updated_at' => '2024-02-06 21:37:55'),
      array('id' => '16','user_id' => '17','birth_date' => '1991-12-22 12:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'г. Душанбе, р-н Сино, ул. Якка-Чинарская 144/3-29','email' => 'mkhakimov@evolet.co.uk','tel_1' => '777100189','tel_2' => NULL,'family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-06 21:44:35','updated_at' => '2024-02-06 21:44:35'),
      array('id' => '17','user_id' => '18','birth_date' => '1990-06-23 13:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'г. Душанбе, ул. Федина 3, кв. 54','email' => 'akmal.sherbadalov@evolet.co.uk','tel_1' => '93400008','tel_2' => NULL,'family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-06 21:49:22','updated_at' => '2024-02-06 21:49:22'),
      array('id' => '18','user_id' => '19','birth_date' => '2000-09-11 13:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'ул. Рудаки,д. 70, кв.36','email' => 'azizjon1001@mail.ru','tel_1' => '937328888','tel_2' => NULL,'family_status' => 'Не женат','children' => NULL,'created_at' => '2024-02-06 22:09:20','updated_at' => '2024-02-06 22:09:20'),
      array('id' => '19','user_id' => '20','birth_date' => '1987-10-22 13:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'г. Душанбе, ул. Балъами 3-й проезд, дом №7','email' => 'azimjon-87@mail.ru','tel_1' => '987208989','tel_2' => '935739292','family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-06 22:22:46','updated_at' => '2024-02-06 22:22:46'),
      array('id' => '20','user_id' => '21','birth_date' => '1980-12-19 12:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'Испечак 2, М-30, д-7, кв. 19','email' => 'sakr-al-bar.8080@mail.ru','tel_1' => '935550861','tel_2' => '907610861','family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-06 22:28:25','updated_at' => '2024-02-06 22:28:25'),
      array('id' => '21','user_id' => '24','birth_date' => '1982-02-12 12:00:00','gender' => 'Женский','nationality' => 'Таджичка','citizenship' => 'РТ','address' => 'ул. Н. Махсум 105/3, кв30','email' => 'zaynabsunatova1982@gmail.com','tel_1' => '87776688','tel_2' => '87777885','family_status' => NULL,'children' => NULL,'created_at' => '2024-02-06 22:48:41','updated_at' => '2024-02-06 22:48:41'),
      array('id' => '22','user_id' => '25','birth_date' => '1990-05-31 13:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'г. Душанбе, ул. А. Гуломова 3, кв. 31','email' => 'daler.kodirov@evolet.co.uk','tel_1' => '90 180 6000','tel_2' => '90 180 6000','family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-06 22:52:59','updated_at' => '2024-02-06 22:52:59'),
      array('id' => '23','user_id' => '26','birth_date' => '1979-11-10 12:00:00','gender' => 'Мужской','nationality' => 'Таджичка','citizenship' => 'РТ','address' => 'г. Душанбе, ул. Мира 30','email' => 'anisa.pdd@evolet.co.uk','tel_1' => '90 783 7788','tel_2' => '90 756 7788','family_status' => 'Замужем','children' => NULL,'created_at' => '2024-02-06 22:58:29','updated_at' => '2024-02-06 22:58:29'),
      array('id' => '24','user_id' => '27','birth_date' => '2000-12-08 12:00:00','gender' => 'Женский','nationality' => 'Таджичка','citizenship' => 'РТ','address' => 'г. Душанбе, 3 проезд Б. Гафурова д.9 кв 17','email' => 'mimrzaripova@gmail.com','tel_1' => '919599947','tel_2' => '772221274','family_status' => 'Не замужем','children' => NULL,'created_at' => '2024-02-06 23:04:12','updated_at' => '2024-02-06 23:04:12'),
      array('id' => '25','user_id' => '28','birth_date' => '2001-01-26 12:00:00','gender' => 'Женский','nationality' => 'Таджичка','citizenship' => 'РТ','address' => 'ул/ Н. Карабаева, дом 67, кв. 82','email' => 'zebokarimova12@gmail.com','tel_1' => '918353196','tel_2' => '772221274','family_status' => 'Не замужем','children' => NULL,'created_at' => '2024-02-06 23:08:04','updated_at' => '2024-02-06 23:08:04'),
      array('id' => '26','user_id' => '29','birth_date' => '1999-01-11 12:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ/РФ','address' => 'ул. Н. Карабаев 24.4 кв 30','email' => 'alim.munavarov@evolet.co.uk','tel_1' => '933049304','tel_2' => '502090199','family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-06 23:12:16','updated_at' => '2024-02-06 23:12:16'),
      array('id' => '27','user_id' => '30','birth_date' => '1992-08-07 13:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'ул. Неъмат Карабаев, д. 63/2, кв. 4','email' => 'olimjon.nuruloev@evolet.co.uk','tel_1' => '900099994','tel_2' => '988004010','family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-06 23:21:44','updated_at' => '2024-02-06 23:21:44'),
      array('id' => '28','user_id' => '31','birth_date' => '2002-03-11 12:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'г.Душанбе, ул. Закариё Рози, д. 12','email' => 'shahriyorp@icloud.com','tel_1' => '552050000','tel_2' => '988004010','family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-06 23:29:32','updated_at' => '2024-02-06 23:29:32'),
      array('id' => '29','user_id' => '32','birth_date' => '1999-05-31 13:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'г. Душанбе, ул. Дехлави д. 6, кв. 8','email' => 'karimov-abdukarim@inbox.ru','tel_1' => NULL,'tel_2' => NULL,'family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-07 00:30:50','updated_at' => '2024-02-07 00:30:50'),
      array('id' => '30','user_id' => '33','birth_date' => '1995-10-08 13:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'р. Рудаки, д. Гулистон, дом 62','email' => 'bekha95@bk.ru','tel_1' => '918 20 6065','tel_2' => '917 20 6065','family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-07 00:34:26','updated_at' => '2024-02-07 00:34:26'),
      array('id' => '31','user_id' => '34','birth_date' => '1992-10-13 13:00:00','gender' => 'Женский','nationality' => 'Таджичка','citizenship' => 'РТ','address' => 'г.Душанбе, улица Ахмади Дониш 22','email' => 'manya.rasulova@gmail.com','tel_1' => '987601172','tel_2' => NULL,'family_status' => 'Замужем','children' => NULL,'created_at' => '2024-02-11 17:48:23','updated_at' => '2024-02-11 18:01:41'),
      array('id' => '32','user_id' => '35','birth_date' => '1995-09-24 13:00:00','gender' => 'Женский','nationality' => 'Таджичка','citizenship' => 'РТ','address' => 'ул.С Курбонов 5 кв 27','email' => 'ms.khumayro@list.ru','tel_1' => '900370102','tel_2' => NULL,'family_status' => 'Не замужем','children' => NULL,'created_at' => '2024-02-11 17:59:57','updated_at' => '2024-02-11 17:59:57'),
      array('id' => '33','user_id' => '36','birth_date' => '1985-07-21 13:00:00','gender' => 'Женский','nationality' => 'Таджичка','citizenship' => 'РТ','address' => 'Душанбе ул. Шоди 6','email' => NULL,'tel_1' => '93 781 88 85','tel_2' => NULL,'family_status' => 'Замужем','children' => NULL,'created_at' => '2024-02-11 18:22:32','updated_at' => '2024-02-11 18:22:32'),
      array('id' => '34','user_id' => '37','birth_date' => '1997-03-11 12:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'РТ, г.Душанбе, ул.Франко 54','email' => 'ehson.alifshoev@gmail.com','tel_1' => '50 107 5557','tel_2' => '50 100 1117','family_status' => 'Не женат','children' => NULL,'created_at' => '2024-02-11 18:30:06','updated_at' => '2024-02-11 18:30:06'),
      array('id' => '35','user_id' => '38','birth_date' => '1987-07-22 13:00:00','gender' => 'Женский','nationality' => 'Таджичка','citizenship' => 'РТ','address' => 'г.  Душанбе, район Сино. ул. Маяковского 4  кв 33','email' => 'sadbargvalieva@gmail.com','tel_1' => '98 871 8760','tel_2' => '888804011','family_status' => 'Не замужем','children' => NULL,'created_at' => '2024-02-11 19:23:20','updated_at' => '2024-02-11 19:23:20'),
      array('id' => '36','user_id' => '39','birth_date' => '1989-03-28 12:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'г.  Душанбе, район Сино. ул. Маяковского 4  кв 33','email' => 'sadbargvalieva@gmail.com','tel_1' => '98 871 8760','tel_2' => '888804011','family_status' => NULL,'children' => NULL,'created_at' => '2024-02-11 21:30:05','updated_at' => '2024-02-11 21:30:05'),
      array('id' => '37','user_id' => '40','birth_date' => '1994-10-04 13:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'г. Душанбе, ул. Клагенфурт 1, кв. 70','email' => 'umedjoni.nemon@gmail.com','tel_1' => '90 577 4425','tel_2' => '93 733 1323','family_status' => 'Не женат','children' => NULL,'created_at' => '2024-02-11 21:36:37','updated_at' => '2024-02-11 21:36:37'),
      array('id' => '38','user_id' => '41','birth_date' => '1992-06-09 13:00:00','gender' => 'Женский','nationality' => 'Таджичка','citizenship' => 'РТ','address' => 'ул. Рудаки,д. 174, кв. 8','email' => 'ominamoh@mail.ru','tel_1' => '927551301','tel_2' => NULL,'family_status' => 'Не замужем','children' => NULL,'created_at' => '2024-02-11 21:51:01','updated_at' => '2024-02-11 21:51:01'),
      array('id' => '39','user_id' => '42','birth_date' => '1995-06-07 13:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'А. Гуломов м1 дом 2/3 кв 6','email' => 'akramtolibov@gmail.com','tel_1' => '987 38 02 26','tel_2' => NULL,'family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-11 21:53:37','updated_at' => '2024-02-11 21:53:37'),
      array('id' => '40','user_id' => '43','birth_date' => '1982-03-30 12:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'А. Гуломов м1 дом 2/3 кв 6','email' => 'akramtolibov@gmail.com','tel_1' => '987 38 02 26','tel_2' => NULL,'family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-11 21:56:15','updated_at' => '2024-02-11 21:56:15'),
      array('id' => '41','user_id' => '44','birth_date' => '1997-02-04 12:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'г.Душанбе, ул.Гипрозем 30/1 кв 100','email' => 'boburjon_n@mail.ru','tel_1' => '90 889 0032','tel_2' => '918 26 6986','family_status' => 'Не женат','children' => NULL,'created_at' => '2024-02-11 22:03:45','updated_at' => '2024-02-11 22:03:45'),
      array('id' => '42','user_id' => '45','birth_date' => '1997-03-20 00:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => NULL,'email' => NULL,'tel_1' => '987654321','tel_2' => NULL,'family_status' => 'Не женат','children' => NULL,'created_at' => '2024-02-11 22:09:15','updated_at' => '2024-03-11 04:42:54'),
      array('id' => '43','user_id' => '46','birth_date' => '1983-01-02 12:00:00','gender' => 'Мужской','nationality' => 'Русский','citizenship' => 'РТ','address' => 'ул. С. Шерози 20/7','email' => 'dendenis83@gmail.com','tel_1' => '933002036','tel_2' => NULL,'family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-11 22:14:19','updated_at' => '2024-02-11 22:14:19'),
      array('id' => '44','user_id' => '47','birth_date' => '1992-06-14 13:00:00','gender' => 'Женский','nationality' => 'Русская','citizenship' => 'РТ','address' => 'ул. Н. Махсум 6/3','email' => 'mirzoeva.anna@evolet.co.uk','tel_1' => '918906464','tel_2' => NULL,'family_status' => 'Замужем','children' => NULL,'created_at' => '2024-02-11 22:17:15','updated_at' => '2024-02-11 22:17:15'),
      array('id' => '45','user_id' => '48','birth_date' => '1996-04-30 13:00:00','gender' => 'Женский','nationality' => 'Таджичка','citizenship' => 'РТ','address' => 'Ул. Алишери Навои 13/1, кв. 22','email' => 'azimovalola7@gmail.com','tel_1' => '901703819','tel_2' => NULL,'family_status' => 'Не замужем','children' => NULL,'created_at' => '2024-02-11 22:20:58','updated_at' => '2024-02-12 00:29:54'),
      array('id' => '46','user_id' => '49','birth_date' => '1991-07-12 13:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ/РФ','address' => 'г.Душанбе, ул. Кандила-Джураева, д. 24','email' => 'sherkholmatov91@yandex.ru','tel_1' => '990550744','tel_2' => NULL,'family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-11 22:23:23','updated_at' => '2024-02-11 22:23:23'),
      array('id' => '47','user_id' => '50','birth_date' => '1980-10-23 13:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'ул. Ч.Расулова 45/4 кв.11','email' => 'f.artykov@evolet.co.uk','tel_1' => '888 777 545','tel_2' => '988 616 234','family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-11 22:29:48','updated_at' => '2024-02-11 22:29:48'),
      array('id' => '48','user_id' => '51','birth_date' => '1999-09-03 00:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'ул. Борбад, д. 30','email' => 'komron0309@gmail.com','tel_1' => '945114111','tel_2' => '902704488','family_status' => 'Не женат','children' => NULL,'created_at' => '2024-02-11 22:34:18','updated_at' => '2024-03-11 10:06:37'),
      array('id' => '49','user_id' => '52','birth_date' => '1998-10-17 13:00:00','gender' => 'Мужской','nationality' => 'Таджичка','citizenship' => 'РТ','address' => 'р. Фирдавси. Дехоти 23/6, кв-80','email' => 't.j1898@mail.ru','tel_1' => '901005243','tel_2' => '988338894','family_status' => 'Не замужем','children' => NULL,'created_at' => '2024-02-11 22:39:49','updated_at' => '2024-02-11 22:39:49'),
      array('id' => '50','user_id' => '53','birth_date' => '1993-08-28 13:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'р. Фирдавси, ул. Дехоти, д. 15/1, кв. 21','email' => 'mirobiddin1993@gmail.com','tel_1' => '888330222','tel_2' => NULL,'family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-11 22:45:26','updated_at' => '2024-02-11 23:00:25'),
      array('id' => '51','user_id' => '54','birth_date' => '2003-04-16 13:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'ул. Сомон, д. 40','email' => 'shamsiddin.mirzoev2002@gmail.com','tel_1' => '886377773','tel_2' => '559524848','family_status' => 'Не женат','children' => NULL,'created_at' => '2024-02-11 23:21:17','updated_at' => '2024-02-11 23:21:17'),
      array('id' => '52','user_id' => '55','birth_date' => '1980-03-30 12:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => NULL,'email' => NULL,'tel_1' => NULL,'tel_2' => NULL,'family_status' => 'Женат','children' => NULL,'created_at' => '2024-02-11 23:28:50','updated_at' => '2024-02-11 23:28:50'),
      array('id' => '53','user_id' => '56','birth_date' => '1997-06-08 13:00:00','gender' => 'Женский','nationality' => 'Таджичка','citizenship' => 'РТ','address' => 'пр .Рудаки, 3 проезд, 42','email' => 'kadirova.sabrina@gmail.com','tel_1' => '935727717','tel_2' => NULL,'family_status' => 'Не замужем','children' => '["Нет детей"]','created_at' => '2024-02-11 23:35:14','updated_at' => '2024-02-11 23:35:14'),
      array('id' => '54','user_id' => '57','birth_date' => '1992-11-20 12:00:00','gender' => 'Женский','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'г. Душанбе. прос. Н. Махсум 87/1 кв.16','email' => 'zabirovns@mail.ru','tel_1' => '985958002','tel_2' => NULL,'family_status' => 'Женат','children' => '["Нет детей"]','created_at' => '2024-02-11 23:44:04','updated_at' => '2024-02-11 23:44:04'),
      array('id' => '55','user_id' => '58','birth_date' => '1996-06-22 13:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'г. Душанбе,ул. Хусейнзаде д. 33','email' => 'amirarbobov@gmail.com','tel_1' => '918155111','tel_2' => NULL,'family_status' => 'Не женат','children' => '["Нет детей"]','created_at' => '2024-02-11 23:48:22','updated_at' => '2024-02-11 23:48:22'),
      array('id' => '56','user_id' => '59','birth_date' => '2002-01-03 12:00:00','gender' => 'Женский','nationality' => 'Таджичка','citizenship' => 'РТ','address' => 'г. Душанбе, С.Шерози д. 31 кв. 85','email' => 'madina.bakhtiyor@mail.ru','tel_1' => '75952929','tel_2' => '901088585','family_status' => 'Не замужем','children' => '["Нет детей"]','created_at' => '2024-02-11 23:51:48','updated_at' => '2024-02-11 23:51:48'),
      array('id' => '57','user_id' => '60','birth_date' => '2002-01-03 12:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'г. Душанбе, С.Шерози д. 31 кв. 85','email' => 'madina.bakhtiyor@mail.ru','tel_1' => '75952929','tel_2' => '901088585','family_status' => 'Женат','children' => '["Нет детей"]','created_at' => '2024-02-11 23:54:52','updated_at' => '2024-02-11 23:54:52'),
      array('id' => '58','user_id' => '61','birth_date' => '2000-10-11 13:00:00','gender' => 'Женский','nationality' => 'Таджичка','citizenship' => 'РТ','address' => 'ул. Деваштич','email' => 'anora.jamshed@mail.ru','tel_1' => '935715885','tel_2' => '552770100','family_status' => 'Замужем','children' => '["Нет детей"]','created_at' => '2024-02-11 23:58:01','updated_at' => '2024-02-11 23:58:01'),
      array('id' => '59','user_id' => '62','birth_date' => '1998-08-18 13:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'г.Душанбе, район Фирдавси, ул. Фирдавси 9/5, кв. 53','email' => 'murod.b@evolet.co.uk','tel_1' => '900995927','tel_2' => NULL,'family_status' => 'Не женат','children' => '["Нет детей"]','created_at' => '2024-02-12 00:04:23','updated_at' => '2024-02-12 00:47:42'),
      array('id' => '60','user_id' => '23','birth_date' => '2000-06-30 13:00:00','gender' => 'Женский','nationality' => 'Таджичка','citizenship' => 'РТ','address' => 'ул. Алишери Навои, дом 13/1, кв.22','email' => 'azimovakamilla7@gmail.com','tel_1' => '937752248','tel_2' => NULL,'family_status' => 'Не замужем','children' => NULL,'created_at' => NULL,'updated_at' => '2024-02-12 16:55:40'),
      array('id' => '62','user_id' => '1','birth_date' => '1992-01-02 12:00:00','gender' => 'Женский','nationality' => 'Лачка','citizenship' => 'РТ/РФ','address' => 'ул. Хусейн-заде,д. 2,кв. 4','email' => 'loliholmatova@gmail.com','tel_1' => '907574547','tel_2' => NULL,'family_status' => 'Замужем','children' => NULL,'created_at' => '2024-02-12 00:24:44','updated_at' => '2024-02-12 16:51:17'),
      array('id' => '63','user_id' => '22','birth_date' => NULL,'gender' => 'Женский','nationality' => 'Таджичка','citizenship' => 'РТ','address' => 'г.Душанбе, ул. Алишера Навои, д.35, кв. 130','email' => 'inonodira64@gmail.com','tel_1' => '918 65 7199','tel_2' => '988253315','family_status' => 'Замужем','children' => NULL,'created_at' => '2024-02-12 17:17:32','updated_at' => '2024-02-12 17:20:13'),
      array('id' => '64','user_id' => '63','birth_date' => '2001-05-10 00:00:00','gender' => 'Мужской','nationality' => 'Узбек','citizenship' => 'РТ','address' => 'г. Душанбе ул. Фурузон 72','email' => 'odiljonovfarhod@gmail.com','tel_1' => '904069900','tel_2' => NULL,'family_status' => 'Не женат','children' => NULL,'created_at' => '2024-03-14 05:56:51','updated_at' => '2024-03-14 05:56:51'),
      array('id' => '65','user_id' => '64','birth_date' => '2006-03-22 00:00:00','gender' => 'Мужской','nationality' => 'Таджик','citizenship' => 'РТ','address' => 'г. Душанбе, ул. А.Навои 12 кв. 37','email' => 'payravisoev22@gmail.com','tel_1' => '918 31 22 20','tel_2' => '55 992 22 20','family_status' => 'Не женат','children' => NULL,'created_at' => '2024-03-20 05:48:15','updated_at' => '2024-03-20 05:48:15')
    );

    foreach ($details as $table) {
      DB::table('details')->insert([
        'id' => $table['id'],
        'user_id' => $table['user_id'],
        'birth_date' => $table['birth_date'],
        'gender' => $table['gender'],
        'nationality' => $table['nationality'],
        'citizenship' => $table['citizenship'],
        'address' => $table['address'],
        'email' => $table['email'],
        'tel_1' => $table['tel_1'],
        'tel_2' => $table['tel_2'],
        'family_status' => $table['family_status'],
        'children' => $table['children'],
        'created_at' => $table['created_at'],
        'updated_at' => $table['updated_at'],
      ]);
    }

    $job_user = array(
      array('job_id' => '1','user_id' => '11'),
      array('job_id' => '1','user_id' => '34'),
      array('job_id' => '2','user_id' => '14'),
      array('job_id' => '2','user_id' => '15'),
      array('job_id' => '2','user_id' => '16'),
      array('job_id' => '3','user_id' => '3'),
      array('job_id' => '4','user_id' => '2'),
      array('job_id' => '5','user_id' => '2'),
      array('job_id' => '6','user_id' => '4'),
      array('job_id' => '7','user_id' => '5'),
      array('job_id' => '8','user_id' => '6'),
      array('job_id' => '9','user_id' => '7'),
      array('job_id' => '10','user_id' => '8'),
      array('job_id' => '11','user_id' => '8'),
      array('job_id' => '12','user_id' => '9'),
      array('job_id' => '13','user_id' => '9'),
      array('job_id' => '14','user_id' => '10'),
      array('job_id' => '15','user_id' => '10'),
      array('job_id' => '16','user_id' => '12'),
      array('job_id' => '17','user_id' => '13'),
      array('job_id' => '18','user_id' => '17'),
      array('job_id' => '18','user_id' => '18'),
      array('job_id' => '18','user_id' => '19'),
      array('job_id' => '18','user_id' => '56'),
      array('job_id' => '19','user_id' => '20'),
      array('job_id' => '20','user_id' => '21'),
      array('job_id' => '21','user_id' => '22'),
      array('job_id' => '21','user_id' => '23'),
      array('job_id' => '21','user_id' => '24'),
      array('job_id' => '22','user_id' => '25'),
      array('job_id' => '22','user_id' => '46'),
      array('job_id' => '23','user_id' => '26'),
      array('job_id' => '23','user_id' => '28'),
      array('job_id' => '24','user_id' => '27'),
      array('job_id' => '25','user_id' => '29'),
      array('job_id' => '25','user_id' => '30'),
      array('job_id' => '25','user_id' => '31'),
      array('job_id' => '25','user_id' => '32'),
      array('job_id' => '25','user_id' => '33'),
      array('job_id' => '26','user_id' => '36'),
      array('job_id' => '27','user_id' => '35'),
      array('job_id' => '28','user_id' => '37'),
      array('job_id' => '28','user_id' => '38'),
      array('job_id' => '28','user_id' => '39'),
      array('job_id' => '28','user_id' => '40'),
      array('job_id' => '28','user_id' => '41'),
      array('job_id' => '28','user_id' => '42'),
      array('job_id' => '28','user_id' => '52'),
      array('job_id' => '29','user_id' => '43'),
      array('job_id' => '30','user_id' => '44'),
      array('job_id' => '30','user_id' => '45'),
      array('job_id' => '31','user_id' => '47'),
      array('job_id' => '32','user_id' => '48'),
      array('job_id' => '32','user_id' => '49'),
      array('job_id' => '32','user_id' => '51'),
      array('job_id' => '33','user_id' => '11'),
      array('job_id' => '33','user_id' => '50'),
      array('job_id' => '34','user_id' => '1'),
      array('job_id' => '35','user_id' => '55'),
      array('job_id' => '38','user_id' => '57'),
      array('job_id' => '38','user_id' => '58'),
      array('job_id' => '38','user_id' => '59'),
      array('job_id' => '38','user_id' => '60'),
      array('job_id' => '38','user_id' => '61'),
      array('job_id' => '38','user_id' => '62'),
      array('job_id' => '38','user_id' => '63'),
      array('job_id' => '38','user_id' => '64'),
      array('job_id' => '39','user_id' => '53'),
      array('job_id' => '40','user_id' => '54')
    );

    foreach ($job_user as $table) {
      DB::table('job_user')->insert([
        'job_id' => $table['job_id'],
        'user_id' => $table['user_id'],
      ]);
    }

    $position_user = array(
      array('position_id' => '1','user_id' => '2'),
      array('position_id' => '1','user_id' => '3'),
      array('position_id' => '2','user_id' => '4'),
      array('position_id' => '2','user_id' => '5'),
      array('position_id' => '2','user_id' => '6'),
      array('position_id' => '2','user_id' => '7'),
      array('position_id' => '2','user_id' => '8'),
      array('position_id' => '2','user_id' => '9'),
      array('position_id' => '2','user_id' => '10'),
      array('position_id' => '2','user_id' => '11'),
      array('position_id' => '2','user_id' => '12'),
      array('position_id' => '2','user_id' => '13'),
      array('position_id' => '3','user_id' => '14'),
      array('position_id' => '3','user_id' => '15'),
      array('position_id' => '3','user_id' => '16'),
      array('position_id' => '4','user_id' => '7'),
      array('position_id' => '4','user_id' => '17'),
      array('position_id' => '4','user_id' => '18'),
      array('position_id' => '4','user_id' => '19'),
      array('position_id' => '4','user_id' => '56'),
      array('position_id' => '5','user_id' => '20'),
      array('position_id' => '5','user_id' => '35'),
      array('position_id' => '6','user_id' => '21'),
      array('position_id' => '7','user_id' => '22'),
      array('position_id' => '7','user_id' => '23'),
      array('position_id' => '7','user_id' => '24'),
      array('position_id' => '8','user_id' => '25'),
      array('position_id' => '8','user_id' => '46'),
      array('position_id' => '9','user_id' => '26'),
      array('position_id' => '9','user_id' => '27'),
      array('position_id' => '9','user_id' => '28'),
      array('position_id' => '11','user_id' => '29'),
      array('position_id' => '11','user_id' => '30'),
      array('position_id' => '11','user_id' => '31'),
      array('position_id' => '11','user_id' => '32'),
      array('position_id' => '11','user_id' => '33'),
      array('position_id' => '12','user_id' => '36'),
      array('position_id' => '13','user_id' => '37'),
      array('position_id' => '13','user_id' => '38'),
      array('position_id' => '13','user_id' => '39'),
      array('position_id' => '13','user_id' => '40'),
      array('position_id' => '13','user_id' => '41'),
      array('position_id' => '13','user_id' => '42'),
      array('position_id' => '13','user_id' => '52'),
      array('position_id' => '14','user_id' => '43'),
      array('position_id' => '15','user_id' => '47'),
      array('position_id' => '16','user_id' => '48'),
      array('position_id' => '16','user_id' => '49'),
      array('position_id' => '16','user_id' => '51'),
      array('position_id' => '17','user_id' => '55'),
      array('position_id' => '18','user_id' => '57'),
      array('position_id' => '18','user_id' => '58'),
      array('position_id' => '18','user_id' => '59'),
      array('position_id' => '18','user_id' => '60'),
      array('position_id' => '18','user_id' => '61'),
      array('position_id' => '18','user_id' => '62'),
      array('position_id' => '18','user_id' => '63'),
      array('position_id' => '18','user_id' => '64'),
      array('position_id' => '19','user_id' => '34'),
      array('position_id' => '20','user_id' => '44'),
      array('position_id' => '20','user_id' => '45'),
      array('position_id' => '21','user_id' => '50'),
      array('position_id' => '22','user_id' => '53'),
      array('position_id' => '23','user_id' => '54'),
      array('position_id' => '24','user_id' => '1')
    );

    foreach ($position_user as $table) {
      DB::table('position_user')->insert([
        'position_id' => $table['position_id'],
        'user_id' => $table['user_id'],
      ]);
    }

    $language_user = array(
      array('language_id' => '1','user_id' => '23','level' => '(А2) – ниже среднего'),
      array('language_id' => '2','user_id' => '23','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '23','level' => '(C1) – продвинутый'),
      array('language_id' => '1','user_id' => '24','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '24','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '24','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '25','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '25','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '25','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '26','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '26','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '26','level' => '(В1) – средний'),
      array('language_id' => '11','user_id' => '26','level' => '(C2) – профессиональный'),
      array('language_id' => '1','user_id' => '27','level' => '(C1) – продвинутый'),
      array('language_id' => '2','user_id' => '27','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '27','level' => '(C1) – продвинутый'),
      array('language_id' => '6','user_id' => '27','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '28','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '28','level' => '(В2) – выше среднего'),
      array('language_id' => '3','user_id' => '28','level' => '(В2) – выше среднего'),
      array('language_id' => '1','user_id' => '29','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '29','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '29','level' => '(C1) – продвинутый'),
      array('language_id' => '1','user_id' => '30','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '30','level' => '(В2) – выше среднего'),
      array('language_id' => '3','user_id' => '30','level' => '(C1) – продвинутый'),
      array('language_id' => '6','user_id' => '30','level' => '(А2) – ниже среднего'),
      array('language_id' => '1','user_id' => '31','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '31','level' => '(В2) – выше среднего'),
      array('language_id' => '3','user_id' => '31','level' => '(В1) – средний'),
      array('language_id' => '7','user_id' => '31','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '32','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '32','level' => '(В2) – выше среднего'),
      array('language_id' => '3','user_id' => '32','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '33','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '33','level' => '(В1) – средний'),
      array('language_id' => '3','user_id' => '33','level' => '(А1) – начальный'),
      array('language_id' => '1','user_id' => '34','level' => '(C1) – продвинутый'),
      array('language_id' => '2','user_id' => '34','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '34','level' => '(В2) – выше среднего'),
      array('language_id' => '1','user_id' => '35','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '35','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '35','level' => '(В2) – выше среднего'),
      array('language_id' => '5','user_id' => '35','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '36','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '36','level' => '(А2) – ниже среднего'),
      array('language_id' => '1','user_id' => '37','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '37','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '37','level' => '(C1) – продвинутый'),
      array('language_id' => '1','user_id' => '38','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '38','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '38','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '39','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '39','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '39','level' => '(А2) – ниже среднего'),
      array('language_id' => '9','user_id' => '39','level' => '(В2) – выше среднего'),
      array('language_id' => '1','user_id' => '40','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '40','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '40','level' => '(C1) – продвинутый'),
      array('language_id' => '1','user_id' => '41','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '41','level' => '(C1) – продвинутый'),
      array('language_id' => '7','user_id' => '41','level' => '(А2) – ниже среднего'),
      array('language_id' => '9','user_id' => '41','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '48','level' => '(В1) – средний'),
      array('language_id' => '2','user_id' => '48','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '48','level' => '(C1) – продвинутый'),
      array('language_id' => '1','user_id' => '49','level' => '(C1) – продвинутый'),
      array('language_id' => '2','user_id' => '49','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '49','level' => '(А2) – ниже среднего'),
      array('language_id' => '1','user_id' => '50','level' => '(В2) – выше среднего'),
      array('language_id' => '2','user_id' => '50','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '50','level' => '(C1) – продвинутый'),
      array('language_id' => '5','user_id' => '50','level' => '(C1) – продвинутый'),
      array('language_id' => '1','user_id' => '51','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '51','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '51','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '53','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '53','level' => '(C1) – продвинутый'),
      array('language_id' => '1','user_id' => '54','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '54','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '54','level' => '(C1) – продвинутый'),
      array('language_id' => '5','user_id' => '54','level' => '(C1) – продвинутый'),
      array('language_id' => '1','user_id' => '55','level' => '(C1) – продвинутый'),
      array('language_id' => '2','user_id' => '55','level' => '(C2) – профессиональный'),
      array('language_id' => '1','user_id' => '56','level' => '(А2) – ниже среднего'),
      array('language_id' => '2','user_id' => '56','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '56','level' => '(C1) – продвинутый'),
      array('language_id' => '7','user_id' => '56','level' => '(C1) – продвинутый'),
      array('language_id' => '1','user_id' => '57','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '57','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '57','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '58','level' => '(А2) – ниже среднего'),
      array('language_id' => '2','user_id' => '58','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '58','level' => '(C2) – профессиональный'),
      array('language_id' => '6','user_id' => '58','level' => '(А1) – начальный'),
      array('language_id' => '1','user_id' => '59','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '59','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '59','level' => '(C1) – продвинутый'),
      array('language_id' => '1','user_id' => '60','level' => '(C1) – продвинутый'),
      array('language_id' => '2','user_id' => '60','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '60','level' => '(В2) – выше среднего'),
      array('language_id' => '6','user_id' => '60','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '22','level' => '(В1) – средний'),
      array('language_id' => '2','user_id' => '22','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '22','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '42','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '42','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '42','level' => '(C1) – продвинутый'),
      array('language_id' => '12','user_id' => '42','level' => '(C1) – продвинутый'),
      array('language_id' => '1','user_id' => '43','level' => '(В2) – выше среднего'),
      array('language_id' => '2','user_id' => '43','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '43','level' => '(C1) – продвинутый'),
      array('language_id' => '5','user_id' => '43','level' => '(C1) – продвинутый'),
      array('language_id' => '1','user_id' => '44','level' => '(C1) – продвинутый'),
      array('language_id' => '2','user_id' => '44','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '44','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '45','level' => '(В2) – выше среднего'),
      array('language_id' => '2','user_id' => '45','level' => '(В1) – средний'),
      array('language_id' => '3','user_id' => '45','level' => '(В1) – средний'),
      array('language_id' => '5','user_id' => '45','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '46','level' => '(В2) – выше среднего'),
      array('language_id' => '2','user_id' => '46','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '46','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '47','level' => '(А2) – ниже среднего'),
      array('language_id' => '2','user_id' => '47','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '47','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '52','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '52','level' => '(В1) – средний'),
      array('language_id' => '3','user_id' => '52','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '61','level' => '(В2) – выше среднего'),
      array('language_id' => '2','user_id' => '61','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '61','level' => '(А1) – начальный'),
      array('language_id' => '1','user_id' => '62','level' => '(В2) – выше среднего'),
      array('language_id' => '2','user_id' => '62','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '62','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '1','level' => '(В1) – средний'),
      array('language_id' => '2','user_id' => '1','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '1','level' => '(В2) – выше среднего'),
      array('language_id' => '7','user_id' => '1','level' => '(В2) – выше среднего'),
      array('language_id' => '1','user_id' => '2','level' => '(C1) – продвинутый'),
      array('language_id' => '2','user_id' => '2','level' => '(В1) – средний'),
      array('language_id' => '3','user_id' => '2','level' => '(В1) – средний'),
      array('language_id' => '5','user_id' => '2','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '3','level' => '(C1) – продвинутый'),
      array('language_id' => '2','user_id' => '3','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '3','level' => '(В1) – средний'),
      array('language_id' => '4','user_id' => '3','level' => '(C1) – продвинутый'),
      array('language_id' => '1','user_id' => '4','level' => '(C1) – продвинутый'),
      array('language_id' => '2','user_id' => '4','level' => '(В1) – средний'),
      array('language_id' => '3','user_id' => '4','level' => '(А1) – начальный'),
      array('language_id' => '1','user_id' => '5','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '5','level' => '(В1) – средний'),
      array('language_id' => '3','user_id' => '5','level' => '(C1) – продвинутый'),
      array('language_id' => '5','user_id' => '5','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '6','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '6','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '6','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '7','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '7','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '7','level' => '(C2) – профессиональный'),
      array('language_id' => '10','user_id' => '7','level' => '(C2) – профессиональный'),
      array('language_id' => '1','user_id' => '8','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '8','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '8','level' => '(В1) – средний'),
      array('language_id' => '4','user_id' => '8','level' => '(C2) – профессиональный'),
      array('language_id' => '1','user_id' => '9','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '9','level' => '(В1) – средний'),
      array('language_id' => '3','user_id' => '9','level' => '(C1) – продвинутый'),
      array('language_id' => '5','user_id' => '9','level' => '(C2) – профессиональный'),
      array('language_id' => '1','user_id' => '10','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '10','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '10','level' => '(C1) – продвинутый'),
      array('language_id' => '13','user_id' => '10','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '11','level' => '(В1) – средний'),
      array('language_id' => '2','user_id' => '11','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '11','level' => '(C1) – продвинутый'),
      array('language_id' => '6','user_id' => '11','level' => '(А1) – начальный'),
      array('language_id' => '1','user_id' => '12','level' => '(А2) – ниже среднего'),
      array('language_id' => '2','user_id' => '12','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '12','level' => '(В1) – средний'),
      array('language_id' => '6','user_id' => '12','level' => '(C1) – продвинутый'),
      array('language_id' => '1','user_id' => '13','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '13','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '13','level' => '(C1) – продвинутый'),
      array('language_id' => '14','user_id' => '13','level' => '(А2) – ниже среднего'),
      array('language_id' => '1','user_id' => '14','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '14','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '14','level' => '(В2) – выше среднего'),
      array('language_id' => '1','user_id' => '15','level' => '(C1) – продвинутый'),
      array('language_id' => '2','user_id' => '15','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '15','level' => '(C1) – продвинутый'),
      array('language_id' => '14','user_id' => '15','level' => '(C1) – продвинутый'),
      array('language_id' => '10','user_id' => '15','level' => '(В1) – средний'),
      array('language_id' => '15','user_id' => '15','level' => '(А1) – начальный'),
      array('language_id' => '1','user_id' => '16','level' => '(C1) – продвинутый'),
      array('language_id' => '2','user_id' => '16','level' => '(В2) – выше среднего'),
      array('language_id' => '3','user_id' => '16','level' => '(А1) – начальный'),
      array('language_id' => '1','user_id' => '17','level' => '(C1) – продвинутый'),
      array('language_id' => '2','user_id' => '17','level' => '(C1) – продвинутый'),
      array('language_id' => '3','user_id' => '17','level' => '(В1) – средний'),
      array('language_id' => '4','user_id' => '17','level' => '(C1) – продвинутый'),
      array('language_id' => '1','user_id' => '18','level' => '(C1) – продвинутый'),
      array('language_id' => '2','user_id' => '18','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '18','level' => '(C1) – продвинутый'),
      array('language_id' => '9','user_id' => '18','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '19','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '19','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '19','level' => '(В2) – выше среднего'),
      array('language_id' => '6','user_id' => '19','level' => '(В2) – выше среднего'),
      array('language_id' => '1','user_id' => '20','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '20','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '20','level' => '(В1) – средний'),
      array('language_id' => '1','user_id' => '21','level' => '(C2) – профессиональный'),
      array('language_id' => '2','user_id' => '21','level' => '(C2) – профессиональный'),
      array('language_id' => '3','user_id' => '21','level' => '(В1) – средний')
    );

    foreach ($language_user as $table) {
      DB::table('language_user')->insert([
        'language_id' => $table['language_id'],
        'user_id' => $table['user_id'],
        'level' => $table['level'],
      ]);
    }
  }
}
